# Generated by Django 3.1.7 on 2021-04-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0005_auto_20210415_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(verbose_name='%m/%d/%y'),
        ),
    ]
