# Generated by Django 3.1.7 on 2021-04-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210420_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activate_date',
            new_name='activate_time',
        ),
    ]
