# Generated by Django 3.1.7 on 2021-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210420_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
