# Generated by Django 3.1.7 on 2021-04-26 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_game_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
