# Generated by Django 3.1.7 on 2021-04-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210428_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='link_time',
            new_name='activation_link_time',
        ),
    ]
