# Generated by Django 3.1.7 on 2021-04-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210428_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
