version: '3'

services:

  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
      - rabbitmq
    ports:
    - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./static/:/static
    depends_on:
      - web
      - postgresdb
    ports:
    - "80:80"

  rabbitmq:
    image: rabbitmq:alpine

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A proj worker -l info
    volumes:
      - .:/code
    depends_on:
      - postgresdb
      - rabbitmq

  celery-beat:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A proj beat -l info
    volumes:
      - .:/code
    depends_on:
      - postgresdb
      - rabbitmq
