version: '3'

services:

  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: gamestore_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:alpine

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_NAME=gamestore_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
    volumes:
    - ./:/usr/src/app
    depends_on:
      - postgresdb
      - rabbitmq
