version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile-gamestore
    environment:
      - DB_NAME=gamestore
      - DB_USER=gamestore
      - DB_PASSWORD=gamestore
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - nginx
