version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=gamestore
      - POSTGRES_USER=gamestore
      - POSTGRES_PASSWORD=gamestore
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:alpine

  app:
    build:
      context: .
      dockerfile: Dockerfile-gamestore
    environment:
      - DB_NAME=gamestore
      - DB_USER=gamestore
      - DB_PASSWORD=gamestore
      - DB_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - nginx
