# Generated by Django 3.1.7 on 2021-05-05 14:26

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_game_genre_image_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='1', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='genre',
            name='game',
        ),
        migrations.AddField(
            model_name='genre',
            name='game',
            field=models.ManyToManyField(related_name='genres', to='board.Game'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.FileField(blank=True, upload_to=board.models.directory_path),
        ),
        migrations.RemoveField(
            model_name='platforms',
            name='game',
        ),
        migrations.AddField(
            model_name='platforms',
            name='game',
            field=models.ManyToManyField(related_name='platforms', to='board.Game'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
