# Generated by Django 3.1.7 on 2021-05-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210505_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('author_id', models.IntegerField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_url', models.CharField(max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='board.game')),
            ],
        ),
    ]
