# Generated by Django 3.1.7 on 2021-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210505_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
