# Generated by Django 3.1.7 on 2021-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20210505_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platforms',
            new_name='Platform',
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
