# Generated by Django 3.1.7 on 2021-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20210508_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aggregated_rating',
            field=models.FloatField(null=True),
        ),
    ]
