# Generated by Django 3.1.7 on 2021-05-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20210508_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload',
        ),
    ]
